add inverted reverse param
ros2/teleop_twist_joy pull request #35
Opened 2023-06-07 10:00 UTC by turtlewizard73

Inverted reverse parameter described in PR #34 reopened to rolling.

2023-06-07 11:37 UTC, clalancette requested changes

2023-06-07 11:37 UTC, clalancette commented on README.md
> +  - Whether to invert turning left-rigth while reversing (useful for differential wheeled robots).
```suggestion
  - Whether to invert turning left-right while reversing (useful for differential wheeled robots).
```

2023-06-07 11:37 UTC, clalancette commented on src/teleop_twist_joy.cpp
> +    "Teleop enable inverted reverse %d.", pimpl_->inverted_reverse);
I think we should only print this if the inverted_reverse is active, so:

```suggestion
  ROS_INFO_COND_NAMED(
    pimpl_->inverted_reverse, "TeleopTwistJoy", "%s", "Teleop enable inverted reverse.");
```

2023-06-07 12:06 UTC, clalancette approved these changes
Looks good to me, thanks for the fixes!

2023-06-07 12:06 UTC, merged

2024-06-11 10:58 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron